spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/item3104254353?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:mysql://121.41.116.214:3306/item3104254353?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: item3104254353
    password: gZcIVs9wpKprwVmX

    #type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名   用QQ登录
    username: 3104254353@qq.com
          #使用的编码
    default-encoding: utf-8
          #移动端客户授权码(在邮箱中设置)
    password: hhzlktzrbofjdeef
    port: 465
    properties:
         mail:
           smtp:
             socketFactory:
               class: javax.net.ssl.SSLSocketFactory


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #驼峰 默认开启
  configuration:
    map-underscore-to-camel-case: true

#    输出到日志文件中 org.apache.ibatis.logging.slf4j.Slf4jImpl
# 如果是控制台 org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
server:
  port: 8888



shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

dandan:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
#token 过期时间 秒 7天
    expire: 604800
    header: Authorization



